# Site settings
title: "Michael Erpenbeck"
email: michael.erpenbeck@gmail.com
description: ""
baseurl: ""
url: "http://erpenbeck.io"
title_description: "SOLID Engineering...continuously delivered."
title_image: "https://www.gravatar.com/avatar/bce41b3dd3507d3ee37f1b2f6f28d2eb?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: 
github_repository: https://github.com/gitmje
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: Erpenbeck
github_username:  gitmje
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/erpenbeck/
google_plus_link: https://plus.google.com/u/0/101992902038469853143/
stackoverflow_link: https://stackoverflow.com/users/574588/undefind?tab=profile/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
