# Site settings
title: "Michael Erpenbeck"
email: michael.erpenbeck@gmail.com
description: ""
baseurl: ""
url: "http://erpenbeck.io"
title_description: "SOLID Engineering...continuously delivered."
title_image: "image.jpg"
google_analytics: "UA-20365477-4"
disqus_account: 
github_repository: https://github.com/gitmje
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: Erpenbeck
github_username:  gitmje
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/erpenbeck/
google_plus_link: https://plus.google.com/u/0/101992902038469853143/
stackoverflow_link: https://stackoverflow.com/users/574588/undefind?tab=profile/
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
